import { productsData } from "./mockup/productsData.js";

async function createProductTable(connection) {
    try {
      await connection.execute(`
          CREATE TABLE products (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          name VARCHAR2(100) NOT NULL,
          brand VARCHAR2(100) NOT NULL,
          price NUMBER(10, 2) NOT NULL,
          quantity NUMBER(10, 2) NOT NULL,
          sold NUMBER(10, 2) NOT NULL,
          rating FLOAT DEFAULT NULL CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5)),
          ismall NUMBER(1) NOT NULL CHECK (isMall IN (0, 1)),
          description VARCHAR2(1000),
          categories VARCHAR2(100),
          images VARCHAR2(10000) NOT NULL,
          PRIMARY KEY (id)
          )
      `);
            
      for (let product of productsData) {
        product.images = product.images[0];
        await connection.execute(`
            INSERT INTO products (name, brand, price, quantity, sold, rating, ismall, description, categories, images)
            VALUES (:name, :brand, :price, :quantity, :sold, :rating, :ismall, :description, :categories, :images)
        `, product, { autoCommit: true });
      }

      console.log('Products inserted successfully');


      console.log('Products table created successfully');
      console.log("---------------")
    } catch (err) {
      console.error('Error occurred:', err);
    }
  }
  
  export default createProductTable;
  
