async function createUserTable(connection) {
  try {
    await connection.execute(`
      CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        username VARCHAR2(100) NOT NULL,
        password VARCHAR2(100) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (username)
      )
    `);

    // Insert default user
    await connection.execute(`
      INSERT INTO users (username, password) VALUES ('user', 'user')
    `, [], { autoCommit: true });

    // Query and log the user that has just been added
    const result = await connection.execute(`
      SELECT * FROM users WHERE username = 'user'
    `);
    console.log("---------------")
    console.log(`User that has just been added:`, result.rows[0]);

    console.log('Users table created successfully');
    console.log("---------------")
  } catch (err) {
    console.error('Error occurred:', err);
  }
}

export default createUserTable